const actionTypes = {
  ADD_CITY_DETAIL: 'ADD_CITY_DETAIL',
  CITY_IS_EMPTY: 'CITY_IS_EMPTY',
  ADD_TEMPERATURE: 'ADD_TEMPERATURE',
  TEMPERATURE_IS_NOT_FOUND: 'TEMPERATURE_IS_NOT_FOUND',
}

export default actionTypes
